// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: nina-api-grpc/github_contribution.proto

package nina_api_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Contribution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContributedAt string `protobuf:"bytes,1,opt,name=contributedAt,proto3" json:"contributedAt,omitempty"`
	Organization  string `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	Repository    string `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	User          string `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Status        string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Contribution) Reset() {
	*x = Contribution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contribution) ProtoMessage() {}

func (x *Contribution) ProtoReflect() protoreflect.Message {
	mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contribution.ProtoReflect.Descriptor instead.
func (*Contribution) Descriptor() ([]byte, []int) {
	return file_nina_api_grpc_github_contribution_proto_rawDescGZIP(), []int{0}
}

func (x *Contribution) GetContributedAt() string {
	if x != nil {
		return x.ContributedAt
	}
	return ""
}

func (x *Contribution) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *Contribution) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *Contribution) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Contribution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetGithubContributionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contributions []*Contribution `protobuf:"bytes,1,rep,name=contributions,proto3" json:"contributions,omitempty"`
}

func (x *GetGithubContributionResponse) Reset() {
	*x = GetGithubContributionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGithubContributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGithubContributionResponse) ProtoMessage() {}

func (x *GetGithubContributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGithubContributionResponse.ProtoReflect.Descriptor instead.
func (*GetGithubContributionResponse) Descriptor() ([]byte, []int) {
	return file_nina_api_grpc_github_contribution_proto_rawDescGZIP(), []int{1}
}

func (x *GetGithubContributionResponse) GetContributions() []*Contribution {
	if x != nil {
		return x.Contributions
	}
	return nil
}

type PostGithubContributionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contributions []*Contribution `protobuf:"bytes,1,rep,name=contributions,proto3" json:"contributions,omitempty"`
}

func (x *PostGithubContributionRequest) Reset() {
	*x = PostGithubContributionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostGithubContributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostGithubContributionRequest) ProtoMessage() {}

func (x *PostGithubContributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostGithubContributionRequest.ProtoReflect.Descriptor instead.
func (*PostGithubContributionRequest) Descriptor() ([]byte, []int) {
	return file_nina_api_grpc_github_contribution_proto_rawDescGZIP(), []int{2}
}

func (x *PostGithubContributionRequest) GetContributions() []*Contribution {
	if x != nil {
		return x.Contributions
	}
	return nil
}

type DeleteGithubContributionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartAt string `protobuf:"bytes,1,opt,name=startAt,proto3" json:"startAt,omitempty"`
	EndAt   string `protobuf:"bytes,2,opt,name=endAt,proto3" json:"endAt,omitempty"`
}

func (x *DeleteGithubContributionRequest) Reset() {
	*x = DeleteGithubContributionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGithubContributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGithubContributionRequest) ProtoMessage() {}

func (x *DeleteGithubContributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGithubContributionRequest.ProtoReflect.Descriptor instead.
func (*DeleteGithubContributionRequest) Descriptor() ([]byte, []int) {
	return file_nina_api_grpc_github_contribution_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteGithubContributionRequest) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *DeleteGithubContributionRequest) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

type ContributionSum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Sum  int32  `protobuf:"varint,2,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (x *ContributionSum) Reset() {
	*x = ContributionSum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContributionSum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionSum) ProtoMessage() {}

func (x *ContributionSum) ProtoReflect() protoreflect.Message {
	mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionSum.ProtoReflect.Descriptor instead.
func (*ContributionSum) Descriptor() ([]byte, []int) {
	return file_nina_api_grpc_github_contribution_proto_rawDescGZIP(), []int{4}
}

func (x *ContributionSum) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ContributionSum) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type ContributionStatistics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sum                 int32              `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	ContributionSumList []*ContributionSum `protobuf:"bytes,2,rep,name=contributionSumList,proto3" json:"contributionSumList,omitempty"`
}

func (x *ContributionStatistics) Reset() {
	*x = ContributionStatistics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContributionStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionStatistics) ProtoMessage() {}

func (x *ContributionStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionStatistics.ProtoReflect.Descriptor instead.
func (*ContributionStatistics) Descriptor() ([]byte, []int) {
	return file_nina_api_grpc_github_contribution_proto_rawDescGZIP(), []int{5}
}

func (x *ContributionStatistics) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *ContributionStatistics) GetContributionSumList() []*ContributionSum {
	if x != nil {
		return x.ContributionSumList
	}
	return nil
}

type GetStatisticsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_nina_api_grpc_github_contribution_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatisticsRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type GetStatisticsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedPullRequestStatistics *ContributionStatistics `protobuf:"bytes,1,opt,name=createdPullRequestStatistics,proto3" json:"createdPullRequestStatistics,omitempty"`
	CommentedStatistics          *ContributionStatistics `protobuf:"bytes,2,opt,name=commentedStatistics,proto3" json:"commentedStatistics,omitempty"`
	ApprovedStatistics           *ContributionStatistics `protobuf:"bytes,3,opt,name=approvedStatistics,proto3" json:"approvedStatistics,omitempty"`
}

func (x *GetStatisticsResponse) Reset() {
	*x = GetStatisticsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsResponse) ProtoMessage() {}

func (x *GetStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_nina_api_grpc_github_contribution_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatisticsResponse) GetCreatedPullRequestStatistics() *ContributionStatistics {
	if x != nil {
		return x.CreatedPullRequestStatistics
	}
	return nil
}

func (x *GetStatisticsResponse) GetCommentedStatistics() *ContributionStatistics {
	if x != nil {
		return x.CommentedStatistics
	}
	return nil
}

func (x *GetStatisticsResponse) GetApprovedStatistics() *ContributionStatistics {
	if x != nil {
		return x.ApprovedStatistics
	}
	return nil
}

// TODO 消す
type ContributionSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date  string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ContributionSummary) Reset() {
	*x = ContributionSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContributionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionSummary) ProtoMessage() {}

func (x *ContributionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionSummary.ProtoReflect.Descriptor instead.
func (*ContributionSummary) Descriptor() ([]byte, []int) {
	return file_nina_api_grpc_github_contribution_proto_rawDescGZIP(), []int{8}
}

func (x *ContributionSummary) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ContributionSummary) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetGithubContributionSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetGithubContributionSummaryRequest) Reset() {
	*x = GetGithubContributionSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGithubContributionSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGithubContributionSummaryRequest) ProtoMessage() {}

func (x *GetGithubContributionSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGithubContributionSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetGithubContributionSummaryRequest) Descriptor() ([]byte, []int) {
	return file_nina_api_grpc_github_contribution_proto_rawDescGZIP(), []int{9}
}

func (x *GetGithubContributionSummaryRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type GetGithubContributionSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PullRequestSummaries []*ContributionSummary `protobuf:"bytes,1,rep,name=pullRequestSummaries,proto3" json:"pullRequestSummaries,omitempty"`
	CommentedSummaries   []*ContributionSummary `protobuf:"bytes,2,rep,name=commentedSummaries,proto3" json:"commentedSummaries,omitempty"`
	ApprovedSummaries    []*ContributionSummary `protobuf:"bytes,3,rep,name=approvedSummaries,proto3" json:"approvedSummaries,omitempty"`
}

func (x *GetGithubContributionSummaryResponse) Reset() {
	*x = GetGithubContributionSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGithubContributionSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGithubContributionSummaryResponse) ProtoMessage() {}

func (x *GetGithubContributionSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nina_api_grpc_github_contribution_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGithubContributionSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetGithubContributionSummaryResponse) Descriptor() ([]byte, []int) {
	return file_nina_api_grpc_github_contribution_proto_rawDescGZIP(), []int{10}
}

func (x *GetGithubContributionSummaryResponse) GetPullRequestSummaries() []*ContributionSummary {
	if x != nil {
		return x.PullRequestSummaries
	}
	return nil
}

func (x *GetGithubContributionSummaryResponse) GetCommentedSummaries() []*ContributionSummary {
	if x != nil {
		return x.CommentedSummaries
	}
	return nil
}

func (x *GetGithubContributionSummaryResponse) GetApprovedSummaries() []*ContributionSummary {
	if x != nil {
		return x.ApprovedSummaries
	}
	return nil
}

var File_nina_api_grpc_github_contribution_proto protoreflect.FileDescriptor

var file_nina_api_grpc_github_contribution_proto_rawDesc = []byte{
	0x0a, 0x27, 0x6e, 0x69, 0x6e, 0x61, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6e, 0x69, 0x6e, 0x61, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x01, 0x0a,
	0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a,
	0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x59, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x69,
	0x6e, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x59,
	0x0a, 0x1d, 0x50, 0x6f, 0x73, 0x74, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x38, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x69, 0x6e, 0x61, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x51, 0x0a, 0x1f, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x22, 0x37, 0x0a, 0x0f,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x73, 0x75, 0x6d, 0x22, 0x73, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x75,
	0x6d, 0x12, 0x47, 0x0a, 0x13, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x75, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x6e, 0x69, 0x6e, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x52, 0x13, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x97, 0x02, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x60, 0x0a, 0x1c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x50, 0x75, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6e, 0x69, 0x6e, 0x61, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x52, 0x1c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x50, 0x75, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x12, 0x4e, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x6e, 0x69, 0x6e, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x13, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x12, 0x4c, 0x0a, 0x12, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x6e, 0x69, 0x6e, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x12, 0x61, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x22, 0x3f, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x39, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x89, 0x02, 0x0a,
	0x24, 0x47, 0x65, 0x74, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x14, 0x70, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e, 0x69, 0x6e, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x14,
	0x70, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x49, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x65,
	0x64, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x6e, 0x69, 0x6e, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x12, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73, 0x12,
	0x47, 0x0a, 0x11, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e, 0x69, 0x6e,
	0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x11, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73, 0x32, 0xa8, 0x03, 0x0a, 0x19, 0x47, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x23, 0x2e, 0x6e, 0x69, 0x6e, 0x61, 0x2e, 0x47, 0x65, 0x74,
	0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x04,
	0x50, 0x6f, 0x73, 0x74, 0x12, 0x23, 0x2e, 0x6e, 0x69, 0x6e, 0x61, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x28, 0x01, 0x12, 0x49, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x25, 0x2e, 0x6e, 0x69, 0x6e, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x65, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x29,
	0x2e, 0x6e, 0x69, 0x6e, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6e, 0x69, 0x6e, 0x61,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x1a, 0x2e, 0x6e, 0x69, 0x6e, 0x61, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6e, 0x69, 0x6e, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x69, 0x6e, 0x67, 0x65, 0x6e, 0x6d, 0x65, 0x2f, 0x6d, 0x61, 0x6d, 0x69, 0x2d,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x6d, 0x61, 0x6d, 0x69, 0x2d, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x6e, 0x69, 0x6e, 0x61, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nina_api_grpc_github_contribution_proto_rawDescOnce sync.Once
	file_nina_api_grpc_github_contribution_proto_rawDescData = file_nina_api_grpc_github_contribution_proto_rawDesc
)

func file_nina_api_grpc_github_contribution_proto_rawDescGZIP() []byte {
	file_nina_api_grpc_github_contribution_proto_rawDescOnce.Do(func() {
		file_nina_api_grpc_github_contribution_proto_rawDescData = protoimpl.X.CompressGZIP(file_nina_api_grpc_github_contribution_proto_rawDescData)
	})
	return file_nina_api_grpc_github_contribution_proto_rawDescData
}

var file_nina_api_grpc_github_contribution_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_nina_api_grpc_github_contribution_proto_goTypes = []interface{}{
	(*Contribution)(nil),                         // 0: nina.Contribution
	(*GetGithubContributionResponse)(nil),        // 1: nina.GetGithubContributionResponse
	(*PostGithubContributionRequest)(nil),        // 2: nina.PostGithubContributionRequest
	(*DeleteGithubContributionRequest)(nil),      // 3: nina.DeleteGithubContributionRequest
	(*ContributionSum)(nil),                      // 4: nina.ContributionSum
	(*ContributionStatistics)(nil),               // 5: nina.ContributionStatistics
	(*GetStatisticsRequest)(nil),                 // 6: nina.GetStatisticsRequest
	(*GetStatisticsResponse)(nil),                // 7: nina.GetStatisticsResponse
	(*ContributionSummary)(nil),                  // 8: nina.ContributionSummary
	(*GetGithubContributionSummaryRequest)(nil),  // 9: nina.GetGithubContributionSummaryRequest
	(*GetGithubContributionSummaryResponse)(nil), // 10: nina.GetGithubContributionSummaryResponse
	(*emptypb.Empty)(nil),                        // 11: google.protobuf.Empty
}
var file_nina_api_grpc_github_contribution_proto_depIdxs = []int32{
	0,  // 0: nina.GetGithubContributionResponse.contributions:type_name -> nina.Contribution
	0,  // 1: nina.PostGithubContributionRequest.contributions:type_name -> nina.Contribution
	4,  // 2: nina.ContributionStatistics.contributionSumList:type_name -> nina.ContributionSum
	5,  // 3: nina.GetStatisticsResponse.createdPullRequestStatistics:type_name -> nina.ContributionStatistics
	5,  // 4: nina.GetStatisticsResponse.commentedStatistics:type_name -> nina.ContributionStatistics
	5,  // 5: nina.GetStatisticsResponse.approvedStatistics:type_name -> nina.ContributionStatistics
	8,  // 6: nina.GetGithubContributionSummaryResponse.pullRequestSummaries:type_name -> nina.ContributionSummary
	8,  // 7: nina.GetGithubContributionSummaryResponse.commentedSummaries:type_name -> nina.ContributionSummary
	8,  // 8: nina.GetGithubContributionSummaryResponse.approvedSummaries:type_name -> nina.ContributionSummary
	11, // 9: nina.GithubContributionService.Get:input_type -> google.protobuf.Empty
	2,  // 10: nina.GithubContributionService.Post:input_type -> nina.PostGithubContributionRequest
	3,  // 11: nina.GithubContributionService.Delete:input_type -> nina.DeleteGithubContributionRequest
	9,  // 12: nina.GithubContributionService.GetSummary:input_type -> nina.GetGithubContributionSummaryRequest
	6,  // 13: nina.GithubContributionService.GetStatistics:input_type -> nina.GetStatisticsRequest
	1,  // 14: nina.GithubContributionService.Get:output_type -> nina.GetGithubContributionResponse
	11, // 15: nina.GithubContributionService.Post:output_type -> google.protobuf.Empty
	11, // 16: nina.GithubContributionService.Delete:output_type -> google.protobuf.Empty
	10, // 17: nina.GithubContributionService.GetSummary:output_type -> nina.GetGithubContributionSummaryResponse
	7,  // 18: nina.GithubContributionService.GetStatistics:output_type -> nina.GetStatisticsResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_nina_api_grpc_github_contribution_proto_init() }
func file_nina_api_grpc_github_contribution_proto_init() {
	if File_nina_api_grpc_github_contribution_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nina_api_grpc_github_contribution_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contribution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nina_api_grpc_github_contribution_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGithubContributionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nina_api_grpc_github_contribution_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostGithubContributionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nina_api_grpc_github_contribution_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGithubContributionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nina_api_grpc_github_contribution_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContributionSum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nina_api_grpc_github_contribution_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContributionStatistics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nina_api_grpc_github_contribution_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatisticsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nina_api_grpc_github_contribution_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatisticsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nina_api_grpc_github_contribution_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContributionSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nina_api_grpc_github_contribution_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGithubContributionSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nina_api_grpc_github_contribution_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGithubContributionSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nina_api_grpc_github_contribution_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nina_api_grpc_github_contribution_proto_goTypes,
		DependencyIndexes: file_nina_api_grpc_github_contribution_proto_depIdxs,
		MessageInfos:      file_nina_api_grpc_github_contribution_proto_msgTypes,
	}.Build()
	File_nina_api_grpc_github_contribution_proto = out.File
	file_nina_api_grpc_github_contribution_proto_rawDesc = nil
	file_nina_api_grpc_github_contribution_proto_goTypes = nil
	file_nina_api_grpc_github_contribution_proto_depIdxs = nil
}
